# Generated by Django 5.2.17 on 2026-10-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='alergeno',
            field=models.CharField(blank=True, choices=[('ninguno', 'Ninguno'), ('pollo', 'Pollo'), ('carne', 'Carne de Res'), ('trigo', 'Trigo')], default='ninguno', max_length=50),
        ),
    ]
